import { Inter } from "next/font/google";
import "./globals.css";
// import favicon from "/favicon.ico";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UiFry | Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="shortcut icon" href={favicon.src} /> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
